version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: april_server:v1
    container_name: backend_server
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app-network

  ses-mailer:
    build:
      context: ./ses-mailer
      dockerfile: Dockerfile
    image: april_ses_mailer:v1
    container_name: ses_mailer
    env_file:
      - ./ses-mailer/.env
    ports:
      - "8000:8000"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_CLIENT_ID: 300308332418-10857pf01ct3q1ihplql5fjucn7ct08q.apps.googleusercontent.com
        VITE_API_BASE_URL: http://localhost:5000
    image: april_client:v1
    container_name: frontend_client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge