version: "3.9"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=emailsanitization@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/acme.json:/acme.json"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ${BACKEND_IMAGE:-backend:latest}
    container_name: backend_server
    env_file:
      - .env_server
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`${DOMAIN:-new551.duckdns.org}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"
      - "traefik.http.services.server.loadbalancer.server.port=5000"
    networks:
      - app-network

  ses-mailer:
    build:
      context: ./ses-mailer
      dockerfile: Dockerfile
    image: ${SES_IMAGE:-ses-mailer:latest}
    container_name: ses_mailer
    env_file:
      - .env_ses
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ses-mailer.rule=Host(`${DOMAIN:-new551.duckdns.org}`) && PathPrefix(`/mail`)"
      - "traefik.http.routers.ses-mailer.entrypoints=websecure"
      - "traefik.http.routers.ses-mailer.tls.certresolver=myresolver"
      - "traefik.http.services.ses-mailer.loadbalancer.server.port=8000"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID:-300308332418-10857pf01ct3q1ihplql5fjucn7ct08q.apps.googleusercontent.com}
        VITE_API_BASE_URL: https://${DOMAIN:-new551.duckdns.org}/api
    image: ${FRONTEND_IMAGE:-frontend:latest}
    container_name: frontend_client
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`${DOMAIN:-new551.duckdns.org}`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=myresolver"
      - "traefik.http.services.client.loadbalancer.server.port=80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge